<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>launch_files</name>
  <version>0.0.0</version>
  <description>Package for launch files</description>
  <maintainer email="moritzgeissler04@gmail.com">mo</maintainer>
  <license>All rights reserved</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>camera_drivers</exec_depend>
  <exec_depend>headlight_drivers</exec_depend>
  <exec_depend>motor_drivers</exec_depend>
  <exec_depend>peripherals_drivers</exec_depend>
  <exec_depend>sensor_drivers</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
